### ISSUE TITLE
Entity Render & Dimensions

### ISSUE THREAD

**Issue by fox3000foxy** [michaljaz/web-minecraft#7]
@michaljaz All entity was rendered expected players
And for go to other dimensions, Mineflayer bot crashes

**Comment by michaljaz** [comment]
Entities I will fix for sure.
But can you share log of game crash?

**Comment by fox3000foxy** [comment]
[records.zip](https://github.com/michaljaz/web-minecraft/files/5970820/records.zip)
[lsannier@estrella web-minecraft-threejs]$ node index prod
Server is running on *:8080
[+] BetaSeal
[+] BanditScript
[+] BetaSeal
[-] BanditScript
/home/lsannier/Desktop/web-minecraft-threejs/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'effects' of undefined
    at Client.<anonymous> (/home/lsannier/Desktop/web-minecraft-threejs/src/index.coffee:54:45)
    at Client.emit (events.js:327:22)
    at FullPacketParser.<anonymous> (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/protodef/src/serializer.js:89:10)
    at FullPacketParser.Transform._read (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Decompressor.ondata (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Decompressor.emit (events.js:315:20)
    at addChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Decompressor.Readable.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Decompressor.Transform.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Decompressor._transform (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/minecraft-protocol/src/transforms/compression.js:52:12)
    at Decompressor.Transform._read (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Decompressor.Transform._write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Decompressor.Writable.write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Splitter.ondata (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Splitter.emit (events.js:315:20)
    at addChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Splitter.Readable.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Splitter.Transform.push (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Splitter._transform (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/minecraft-protocol/src/transforms/framing.js:61:16)
    at Splitter.Transform._read (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Splitter.Transform._write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Splitter.Writable.write (/home/lsannier/Desktop/web-minecraft-threejs/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Decipheriv.ondata (internal/streams/readable.js:719:22)
    at Decipheriv.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Decipheriv.Readable.push (internal/streams/readable.js:223:10)
    at Decipheriv.Transform.push (internal/streams/transform.js:166:32)
    at Decipheriv._transform (internal/crypto/cipher.js:135:8)
    at Decipheriv.Transform._read (internal/streams/transform.js:205:10)
    at Decipheriv.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Decipheriv.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

[lsannier@estrella web-minecraft-threejs]$ ^C
[lsannier@estrella web-minecraft-threejs]$  cd /tmp/mozilla_lsannier0/
[lsannier@estrella mozilla_lsannier0]$

**Comment by fox3000foxy** [comment]
i add a video for you

**Comment by fox3000foxy** [comment]
And if you can, please add Controls change

**Comment by fox3000foxy** [comment]
Can I be contributor please ?

**Comment by michaljaz** [comment]
Of course, joint discord od repo: https://discord.gg/h6DQzDx2G7
